# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

[default]
account = "RETAILTECH_SANDBOX"
user = "SPANDEY5@LULULEMON.COM"
password = "S@ibaba@12198722"
role = "DEVELOPER_ROLE"
warehouse = "DEVELOPER_WH"
database = "POC_SNOWPARK_DB"
schema = "ANALYTICS"